"""empty message

Revision ID: 74e41d5e8c11
Revises: a60a572a8ade
Create Date: 2024-02-28 19:25:37.029440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e41d5e8c11'
down_revision = 'a60a572a8ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardId', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=35),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=35),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('cover')

    op.drop_table('labels')
    # ### end Alembic commands ###
