"""empty message

Revision ID: a60a572a8ade
Revises: bf4a5e50b63c
Create Date: 2024-01-22 19:24:16.920035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60a572a8ade'
down_revision = 'bf4a5e50b63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cards',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('card_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    # ### end Alembic commands ###
